# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '79d1495d-b595-4b65-ae67-e4513328828d'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    #
    # Symfony behind Balancer
    # @see https://symfony.com/doc/current/deployment/proxies.html
    #
    # the IP address (or range) of your proxy
    trusted_proxies: '172.27.129.14,172.27.128.25'
    # trust *all* "X-Forwarded-*" headers
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
