security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    # https://symfony.com/doc/5.4/security/custom_authenticator.html
    enable_authenticator_manager: true  # todo - remove on symfony6

    providers:
        api:
            id: VysokeSkoly\ImageApi\Service\Security\ApiKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless: true

        api:
            pattern: ^/
            stateless: true
            custom_authenticators:
                - VysokeSkoly\ImageApi\Service\Security\ApiKeyAuthenticator
            provider: api

    access_control:
        # require ROLE_API for all routes except home: /
        - { path: '^/.+', roles: ROLE_API }
