# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        api:
            id: VysokeSkoly\ImageApi\Service\Security\ApiKeyUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            stateless: true

        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: VysokeSkoly\ImageApi\Service\Security\ApiKeyAuthenticator
            provider: api
