version: '3'
services:
    deployment:
        image: dcreg.devel:5000/vysokeskoly-php-deployment:8.1
        volumes:
            - ./..:/srv/www/app
            - /srv/www/app/var/cache    # ignore dir in the docker
        working_dir: /srv/www/app
