# This file is a "template" of what your parameters.yml file should look like
# Set parameters here that may be different on each deployment target of the app, e.g. development, staging, production.
# https://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration
parameters:
    # A secret key that's used to generate certain security-related tokens
    secret: '%env(resolve:APP_SECRET)%'

    api_key: '%env(resolve:API_KEY)%'

    storage_path: '%env(resolve:STORAGE_PATH)%'
    default_namespace: '%env(resolve:DEFAULT_NAMESPACE)%'
